### ISSUE TITLE
Outdated Not Working

### ISSUE THREAD

**Issue by RedShadow5298** [ezz-dev/embed-selfbot#1]
I follow every single step. It's not working. Maybe it's due to the discord update. Or the API not responding. Please help me to fix this problem. thx!
![image](https://user-images.githubusercontent.com/71120631/142869613-18cc3d65-12f9-46aa-960c-5d39e646d3b1.png)

**Comment by Just-A-Noname** [comment]
Discord made some changes in the classes. It should fix it if you just type "window." before every "webpackJsonp"

**Comment by shmeowker** [comment]
Fixed
